steps:
  - name: 'gcr.io/cloud-builders/docker'
    script: |
      docker build -f Dockerfile.stg --platform linux/amd64 -t asia-northeast1-docker.pkg.dev/$PROJECT_ID/mcs-fs-stg-inventory-repo/stg-mcs-inventory-run .
    automapSubstitutions: true
images:
  - 'asia-northeast1-docker.pkg.dev/$PROJECT_ID/mcs-fs-stg-inventory-repo/stg-mcs-inventory-run'
